server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.129:3306/gwdb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: gwuser
    password: gw1994.

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wei.com.wei.springcloud.entities

eureka:
  client:
    #true表示将自己注册进eureka server
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

PAYMENT-SERVICE:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #超时时间
    ReadTimeout: 5000
    #连接时间
    ConnectTimeout: 5000
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
logging:
  level:
    # feign日志以什么级别级别监控哪个接口
    com.wei.springcloud.otherservice.PaymentService: debug

feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true